name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'john-psina'
    environment:
      name: pypi
      url: https://pypi.org/p/django-admin-monaco-editor

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release
          pip install build twine

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Semantic Release
        id: semantic
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          semantic-release publish

      - name: Clean dist directory
        run: rm -rf dist/

      - name: Build package
        id: build
        run: |
          python -m build
          if [ -d "dist" ] && [ "$(ls -A dist)" ]; then
            echo "has_dist=true" >> $GITHUB_OUTPUT
          else
            echo "has_dist=false" >> $GITHUB_OUTPUT
          fi

      - name: Check package
        if: steps.build.outputs.has_dist == 'true'
        run: twine check dist/*

      - name: Publish to PyPI
        if: steps.build.outputs.has_dist == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true

